version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'salt-postgres'
    environment:
      - POSTGRES_USER=anthony
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

